### ISSUE TITLE
Alternator.txt Really ban

### ISSUE THREAD

**Issue by Igors7999** [mgsweet/Apex-NoRecoil-2021#174]
Can you fix this recoil pattern?

**Comment by Igors7999** [comment]
[Devotion.txt](https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/AHK/src/pattern/Devotion.txt) 
[Havoc.txt](https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/AHK/src/pattern/Havoc.txt)
[Hemlok.txt](https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/AHK/src/pattern/Hemlok.txt)
Also needs to be fixed
Can you make a major pattern update?

**Comment by Senixisded** [comment]
@Igors7999 Try toning down the 3rd value(the speed value) in the recoil patterns that you think are too strong (x, y, speed).
You can do this using the Replace function in Notepad and Notepad++, tone it down to around 1 number, or reduce it by a few decimals.
I changed my alternator pattern to use 13.6 instead of the default value, it's a bit calmer now and doesn't pull down that much.
If you want the opposite of making it calmer and wanna make it stronger, tone the 3rd value up ( I haven't tried this)

**Comment by mgsweet** [comment]
check v1.3.8?
