### ISSUE TITLE
turbo havoc doesnt have pattern and wrote in code (apexmaster.ahk)

### ISSUE THREAD

**Issue by iroywang** [mgsweet/Apex-NoRecoil-2021#204]

**Comment by Eternal-Walnut** [comment]
[This pattern is havoc with a turbocharger](https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/AHK/src/pattern/Havoc.txt)
Havoc is different from Devotion, because havoc has no recoil in the first few seconds without a turbocharger
so let's look at the code
![image](https://user-images.githubusercontent.com/100213430/208594908-dd620130-f0d1-43f1-a06d-280fa3c58047.png)
so havoc without turbocharger does not need new pattern
