### ISSUE TITLE
Please do more resolution for wide screen 2560x1080

### ISSUE THREAD

**Issue by PanachaiThongpaiwan** [mgsweet/Apex-NoRecoil-2021#214]
Please do more resolution for wide screen 2560x1080

**Comment by Kartulin** [comment]
+1

**Comment by romabord** [comment]
@PanachaiThongpaiwan @Kartulin 
I just made config to support 2560x1080 resolution, works well with every gun for me + supports turbocharger. I've also added single mode but didn't test it since I don't use it in terms of safety.
I must say that I keep +0,3-0.5 sensitivity in game (1.5 in gui, 1.8-2.0 in game), feels much better for me.
[customized.zip](https://github.com/mgsweet/Apex-NoRecoil-2021/files/10548865/customized.zip)

**Comment by Sissidark** [comment]
> @PanachaiThongpaiwan @Kartulin I just made config to support 2560x1080 resolution, works well with every gun for me + supports turbocharger. I've also added single mode but didn't test it since I don't use it in terms of safety. I must say that I keep +0,3-0.5 sensitivity in game (1.5 in gui, 1.8-2.0 in game), feels much better for me. [customized.zip](https://github.com/mgsweet/Apex-NoRecoil-2021/files/10548865/customized.zip)

great work!ty
