### ISSUE TITLE
Tientie/vengfulcrop Adobe After Effects method

### ISSUE THREAD

**Issue by filen1** [mgsweet/Apex-NoRecoil-2021#23]
https://github.com/vengefulcrop/AE-Recoil-Pattern-Generation/

This method can create incredibly accurate patterns.

**Comment by krampus-nuggets** [comment]
Interesting, I'll look into it. Adobe has a history of not being automation friendly though and it seems to be a bunch of manual overhead both in install and setup of Adobe Suite and actually knowing how to use After Effects. There's also converting the end value so that it's actually usable in our project.

I have a feeling the process can be automated with some computer vision trickery and calculation.

**Comment by mgsweet** [comment]
> I have a feeling the process can be automated with some computer vision trickery and calculation.

When it comes to CV, I am currently doing some research on how to use PoseNet to create an undetectable aimbot.

**Comment by krampus-nuggets** [comment]
> > I have a feeling the process can be automated with some computer vision trickery and calculation.
> 
> When it comes to CV, I am currently doing some research on how to use PoseNet to create an undetectable aimbot.

Nice, I've come across a similar project in the past. It used a pretty performant method for detection using CNN. Here's the link if you're interested - [Link](https://arxiv.org/abs/2004.10934)

On my end however I'm hoping Point Feature Matching will do the trick, we'll see I guess.

**Comment by krampus-nuggets** [comment]
@mgsweet - mentioned this in his notes post and I added it to the tasks for the Python Build project.
