### ISSUE TITLE
Color filter problem

### ISSUE THREAD

**Issue by moayadd** [mgsweet/Apex-NoRecoil-2021#4]
tried my sens also nothing happened ,350 uncomment 351 ; ,, also nothing happened

**Comment by mgsweet** [comment]
So what you mean is, it did work before but now it doesn’t work? But I just updated it today and have finished the testing this morning. 

If this is your first time to use the script, I think what you mean is nothing happens after you run the script. This is because no GUI or tips are provided. Pls try it after you pick a weapon.

If there is really some problems, please provide more details. Such as a demo video, e.g.

**Comment by moayadd** [comment]
Update : turns out that when u change some color etc settings in GeForce overlay Alt+F3 doesnt work . I used no filter and it worked .

what causes the pixels to change ? Colors and vibrence etc? 

Thank you

**Comment by mgsweet** [comment]
@moayadd color

**Comment by mgsweet** [comment]
Solved
