### ISSUE TITLE
How to Compile AHK Script and Python Script

### ISSUE THREAD

**Issue by CplusBest** [mgsweet/Apex-NoRecoil-2021#49]
I am shocked that the capacity of exe file, "apexmaster-v1.2.4.exe" , is only 1.2MB. I thought it would be bigger.  But I have a problem about how to compile and release the exe file. I tried to compile the file in path '/AHK/src/compile/compile.ahk' (I uncommeted the icon sentence) but the output do not have GUI and I did not konw weather it really worked. What's more, you give the python source. According my experience, the exe file released from python will be huge. Maybe I am wrong. Can you provide python version release file?

**Comment by krampus-nuggets** [comment]
@CplusBest - Not too sure what the issue is with the AHK Script @mgsweet should be able to help you there. He's done a lot of updates to the script and I've only recently been able to review the repo.

Yes, the Python build is huge in comparison. You can find it here - [Link](https://github.com/mgsweet/Apex-NoRecoil-2021/releases/tag/v1.0.0)

The Python build is justified for whether you regard ease-of-use above all else. However, I would not recommend trying to compile it yourself unless you know what you're doing. It's not complex, just a lot of annoying hoops to jump through. Also, the AHK script is miles ahead in regards to features at the moment.

**Comment by mgsweet** [comment]
@CplusBest Did u have AutoHotKey installed on your PC? If u cannot run the script, you can use the AHK build-in `convert .ahk to .exe` to build your files. For more information., search how to compile AHK in Google.
