### ISSUE TITLE
Ban investigation

### ISSUE THREAD

**Issue by HFRWi** [mgsweet/Apex-NoRecoil-2021#61]
First is fist, special thanks to mgsweet for this incredible tool and I'm a big fan of your work. Then myself used the tool for couple of days with no problem's. 1.2.4 version. I saw some of users reported that they got banned. we need to see if this manual ban or anti cheap ban. Therefore who ever got banned need to report his ban and how possibly he got it. Like abusing the tool with high DMG and KILLS or spoke about it with random player or just was too obvious that he running the tool. Then after we might come to conclusion why there is a ban. Thanks all for your time.

**Comment by Nymph831** [comment]
Run gui Security.

**Comment by HFRWi** [comment]
what if we try to bypass EAC cuz it seems to be the problem.

**Comment by CalvoG** [comment]
I've been testing the AHK script since season 5 and I've had 3 bans so far, no biggie they were throwaway accounts. From everything I've tested and tried you will only receive a ban if you

1. use the auto-fire  and/or gold optic feature
2. Start origin or apex before opening gui and hider first. Only open Origin after you see "ahk hidden" and click okay. Not sure why the original poster says hider does nothing and its not needed, you will definitely get an almost instant ban if an ahk process is easily visible to EAC.
3. Abuse the script by getting crazy number of kills and obviously beaming people with ease (R-99/R301)
4. Receive reports from other players for obviously using no-recoil. REMEMBER people can spectate you after you kill them. Use common sense. If you receive enough reports from players I'm sure a moderator will spectate your screen and decide if you're cheating. Just don't go crazy and pretend like someone always spectating you.

**Comment by mgsweet** [comment]
Check the latest version: https://github.com/mgsweet/Apex-NoRecoil-2021/issues/69
