### ISSUE TITLE
Issues about Python version

### ISSUE THREAD

**Issue by I-nsAnity** [mgsweet/Apex-NoRecoil-2021#82]

**Comment by I-nsAnity** [comment]
1.How do I make sure that the script is running safely?
Should I use pyinstaller on this script then run .exe? Is this safer?

2.The script compensates too much.
It keeps dragging the view down. The effect is bad.
For patterns in recoil_patterns.py like [-3.5,10.4,0.080]
I use
`#data["modifier_value"]=1
win32api.mouse_event(0x0001, int(-3.5/data["modifier_value"]), int(10.4/data["modifier_value"]))
time.sleep(0.080)`

3.I have chi_sim.traineddata for weap_name,if I can solve the problem on compensating with your help, I would take pl to make chi_sim support.

Excuse me, my English is poor. :D

**Comment by I-nsAnity** [comment]
Sorry,I dont know how to make line feeds

**Comment by krampus-nuggets** [comment]
@I-nsAnity 

1. The script, as of the time of writing, is currently using the win32 API to apply mouse movements this is not safe. There is a pull request out that uses a custom solution which should help with that. The script is not on their radar at the moment but the win32 version could easily be detected.
2. The pull request that is out has also applied the updated recoil values so that should fix your issue. I tested it myself.
3. I'm not too sure what you meant by your 3rd point but I am assuming that you're looking to apply your own recoil values? The recoil values are stored in **python/modules/recoil_patterns.py**, in a nested list where each list contains the following values **[x-coordinate, y-coordinate, shot-delay]**

Does the above info help solve your issues?

**Comment by I-nsAnity** [comment]
Thank you.
